[package]
name = "medium-to-markdown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.12.3"
tokio = { version = "1.37.0", features = ["full"] }
html_parser = "0.7.0"
